author: xHexed
name: LeaderMobs
main: com.github.xhexed.leadermobs.LeaderMobs
version: ${version}
api-version: "1.21.1"
softdepend: [MythicMobs, EliteMobs, PlaceholderAPI]
commands:
  lm:
    usage: /lm
    aliases: [leadermobs]
permissions:
  lm.reload:
    default: op
  lm.toggle:
    default: op